export const API_ROUTES = {
  AUTH: {
    PROFILE: '/auth/profile',
  },
  APPEALS: {
    BASE: '/appeals',
    BY_ID: (id: string) => `/appeals/${id}` as const,
    GENERATE: (id: string) => `/appeals/${id}/generate` as const,
    PREVIEW: (id: string) => `/appeals/${id}/preview` as const,
    PRICING: (id: string) => `/appeals/${id}/pricing` as const,
    UPLOAD: (id: string) => `/appeals/${id}/upload` as const,
    PAY: (id: string) => `/appeals/${id}/pay` as const,
    PAYMENT_STATUS: (id: string) => `/appeals/${id}/payment-status` as const,
    DOWNLOAD: (id: string) => `/appeals/${id}/document` as const,
  },
  VEHICLES: {
    BASE: '/vehicles',
    BY_ID: (id: string) => `/vehicles/${id}` as const,
    SET_DEFAULT: (id: string) => `/vehicles/${id}/default` as const,
  },
  PAYMENTS: {
    BASE: '/payments',
    BY_ID: (id: string) => `/payments/${id}` as const,
    WEBHOOK: '/payments/webhook',
  },
  PROFILE: {
    BASE: '/users/me',
    PREFERENCES: '/users/me',
    CHANGE_PASSWORD: '/users/me/password',
    SESSIONS: '/users/me/sessions',
    SESSION_BY_ID: (id: string) => `/users/me/sessions/${id}` as const,
    DATA_EXPORT: '/users/me/data-export',
    DATA_EXPORT_DOWNLOAD: '/users/me/data-export/download',
    DELETE_REQUEST: '/users/me/delete-request',
    REVOKE_CONSENT: '/users/me/revoke-consent',
  },
  AFFILIATES: {
    BASE: '/affiliates',
    APPLY: '/affiliates/apply',
    ME: '/affiliates/me',
    ME_LINK: '/affiliates/me/link',
    ME_WITHDRAWALS: '/affiliates/me/withdrawals',
    ME_CONVERSIONS: '/affiliates/me/conversions',
  },
  NOTIFICATIONS: {
    BASE: '/notifications',
    COUNT: '/notifications/count',
    MARK_READ: (id: string) => `/notifications/${id}/read` as const,
    MARK_ALL_READ: '/notifications/read-all',
  },
  CTB: {
    INFRACTIONS: '/ctb/infractions',
    SEARCH: '/ctb/infractions/search',
  },
} as const;
