export const APP_ROUTES = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    VERIFY_EMAIL: '/auth/verify-email',
    CALLBACK: '/auth/callback',
  },
  APP: {
    DASHBOARD: '/',
    NEW_APPEAL: '/appeals/new',
    APPEAL_DETAIL: '/appeals/:id',
    APPEAL_PREVIEW: '/appeals/:id/preview',
    APPEAL_GENERATING: '/appeals/:id/generating',
    PAYMENT: '/payment/:id',
    PAYMENT_PIX: '/payment/:id/pix',
    PAYMENT_SUCCESS: '/payment/:id/success',
    HISTORY: '/history',
    HISTORY_DETAIL: '/history/:id',
    PROFILE: '/profile',
    VEHICLES: '/profile/vehicles',
    CHANGE_PASSWORD: '/profile/change-password',
    PRIVACY: '/profile/privacy',
    DELETE_ACCOUNT: '/profile/delete-account',
    AFFILIATE: '/affiliate',
    AFFILIATE_APPLY: '/affiliate/apply',
    AFFILIATE_WITHDRAWALS: '/affiliate/withdrawals',
    NOTIFICATIONS: '/notifications',
  },
  EXTERNAL: {
    LANDING: 'https://justifica.ai',
    TERMS: 'https://justifica.ai/termos',
    PRIVACY: 'https://justifica.ai/privacidade',
  },
} as const;
